---
version: "3.4"

services:

  ################## Live Events Application ###################
  music_store_application:
    build:
      context: .
      dockerfile: Music-Store-Application/Dockerfile
    image: music-store-application
    container_name: music-store-application
    extra_hosts:
      - "localhost:192.168.65.2"
    ports:
      - 8084:8080
      - 6569:6565
    environment:
      - AWS_ACCESS_KEY_ID=anykey
      - AWS_SECRET_ACCESS_KEY=anysecret
      - AWS_REGION=us-east-1
    volumes:
      - ${MUSIC_STORE_APPLICATION_PATH}:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local/root:/root
    # depends_on:
    #   - awssetup
    tty: true

networks:
  default:
    driver: overlay
    name: local-music-store
    attachable: true